/* 制作の書斎 — 自炊本から変形した種火
 *
 * 本文の転載ではなく、knowledge/e-books pdf/内容要約 に記録された確認済みの論点を、
 * 「未完成の一行場面」へ変形したもの。要確認扱いの本は使わない。
 * bookSources は下の SHOSAI_BOOK_SOURCES を参照し、出典と変形の境界を表示する。
 */

const SHOSAI_BOOK_SOURCES = {
  world_making: {
    title: "世界観の作り方",
    category: "01 写真・デザイン",
    summaryPath: "knowledge/e-books pdf/内容要約/01_写真・デザイン/世界観の作り方.md",
  },
  photo_story: {
    title: "ストーリーを語る、写真の撮り方",
    category: "01 写真・デザイン",
    summaryPath: "knowledge/e-books pdf/内容要約/01_写真・デザイン/ストーリーを語る、写真の撮り方.md",
  },
  improv: {
    title: "〈インプロ〉即興の技術【改訂版】",
    category: "02 音楽・エンターテインメント",
    summaryPath: "knowledge/e-books pdf/内容要約/02_音楽・エンターテインメント/〈インプロ〉即興の技術【改訂版】.md",
  },
  neiro: {
    title: "NEIRO",
    category: "02 音楽・エンターテインメント",
    summaryPath: "knowledge/e-books pdf/内容要約/02_音楽・エンターテインメント/NEIRO.md",
  },
  noh_kyogen: {
    title: "教養として学んでおきたい能・狂言",
    category: "02 音楽・エンターテインメント",
    summaryPath: "knowledge/e-books pdf/内容要約/02_音楽・エンターテインメント/教養として学んでおきたい能・狂言.md",
  },
  conversation: {
    title: "会話の0.2秒を言語学する",
    category: "03 言語・語学",
    summaryPath: "knowledge/e-books pdf/内容要約/03_言語・語学/会話の0.2秒を言語学する.md",
  },
  speech_sound: {
    title: "音とことばのふしぎな世界",
    category: "03 言語・語学",
    summaryPath: "knowledge/e-books pdf/内容要約/03_言語・語学/音とことばのふしぎな世界.md",
  },
  visual_thinker: {
    title: "ビジュアル・シンカーの脳",
    category: "04 科学・技術",
    summaryPath: "knowledge/e-books pdf/内容要約/04_科学・技術/ビジュアル・シンカーの脳.md",
  },
  beautiful_experiments: {
    title: "世界で最も美しい10の科学実験",
    category: "04 科学・技術",
    summaryPath: "knowledge/e-books pdf/内容要約/04_科学・技術/世界で最も美しい10の科学実験.md",
  },
  bayes: {
    title: "図解・ベイズ統計「超」入門",
    category: "04 科学・技術",
    summaryPath: "knowledge/e-books pdf/内容要約/04_科学・技術/図解・ベイズ統計「超」入門.md",
  },
  container: {
    title: "コンテナ物語",
    category: "05 歴史・地理・社会",
    summaryPath: "knowledge/e-books pdf/内容要約/05_歴史・地理・社会/コンテナ物語.md",
  },
  viewpoints: {
    title: "視点という教養",
    category: "05 歴史・地理・社会",
    summaryPath: "knowledge/e-books pdf/内容要約/05_歴史・地理・社会/視点という教養.md",
  },
  observation: {
    title: "観察力の鍛え方",
    category: "06 経済・ビジネス",
    summaryPath: "knowledge/e-books pdf/内容要約/06_経済・ビジネス/観察力の鍛え方.md",
  },
  thinking: {
    title: "こうやって、考える。",
    category: "06 経済・ビジネス",
    summaryPath: "knowledge/e-books pdf/内容要約/06_経済・ビジネス/こうやって、考える。.md",
  },
  story_notebook: {
    title: "クリエイターのための物語創作ノート 改訂版",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/クリエイターのための物語創作ノート 改訂版.md",
  },
  fantasy_world: {
    title: "クリエイターのためのファンタジー世界構築教典",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/クリエイターのためのファンタジー世界構築教典.md",
  },
  mystery: {
    title: "ミステリが最強の文芸である",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/ミステリが最強の文芸である.md",
  },
  random_reading: {
    title: "乱読のセレンディピティ",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/乱読のセレンディピティ.md",
  },
  cooking_tetrahedron: {
    title: "料理の四面体",
    category: "08 暮らし・料理",
    summaryPath: "knowledge/e-books pdf/内容要約/08_暮らし・料理/料理の四面体.md",
  },
  brain_music: {
    title: "脳と音楽 基礎から身につく「大人の教養」",
    category: "04 科学・技術",
    summaryPath: "knowledge/e-books pdf/内容要約/04_科学・技術/脳と音楽 基礎から身につく「大人の教養」.md",
  },
  propaganda: {
    title: "たのしいプロパガンダ",
    category: "05 歴史・地理・社会",
    summaryPath: "knowledge/e-books pdf/内容要約/05_歴史・地理・社会/たのしいプロパガンダ.md",
  },
  linguistic_rap: {
    title: "言語学的ラップの世界",
    category: "02 音楽・エンターテインメント",
    summaryPath: "knowledge/e-books pdf/内容要約/02_音楽・エンターテインメント/言語学的ラップの世界.md",
  },
  chord_theory: {
    title: "コード理論大全",
    category: "02 音楽・エンターテインメント",
    summaryPath: "knowledge/e-books pdf/内容要約/02_音楽・エンターテインメント/コード理論大全.md",
  },
  naming: {
    title: "プロの小説家が教える 名付けの技法書",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/プロの小説家が教える 名付けの技法書.md",
  },
  mysteries: {
    title: "クリエイターのための怪異図鑑",
    category: "07 小説・文学",
    summaryPath: "knowledge/e-books pdf/内容要約/07_小説・文学/クリエイターのための怪異図鑑.md",
  },
};

const SHOSAI_BOOK_SEEDS = [
  { id: "book-seed-001", recipe: "規則の浸透", dist: "near",
    text: "演者が一歩進むたび、舞台地図から帰り道が一本ずつ消える。最後の道だけは未定。",
    bookSources: ["world_making"],
    inspiration: "地図・移動経路・ランドマークを一貫した世界の規則にする論点を、歩くほど帰路が減る場面へ変形した。" },
  { id: "book-seed-002", recipe: "形の共通言語", dist: "mid",
    text: "衣装、道具、照明が同じ三角形を繰り返す。最初に規則を破るのは誰か。",
    bookSources: ["world_making"],
    inspiration: "形・素材・色に共通規則を持たせる設計を、三つの舞台要素が共有する形の文法へ移した。" },
  { id: "book-seed-003", recipe: "暮らしから逆算", dist: "mid",
    text: "壁の傷、靴の減り、道具の持ち手だけで、ここに住む者の一日を見せる。",
    bookSources: ["world_making"],
    inspiration: "人物の暮らしや技術を建築・道具・衣装へ相互接続する論点から、本人を出さず生活を見せる場面にした。" },
  { id: "book-seed-004", recipe: "設定の受け渡し", dist: "alien",
    text: "一枚の風景画だけを渡され、七人が別々の方法で同じ世界を再建する。",
    bookSources: ["world_making"],
    inspiration: "設定を一枚絵や図解へ変換して共有する工程を、解釈のずれ自体が見える集団制作へ変形した。" },

  { id: "book-seed-005", recipe: "距離の編集", dist: "near",
    text: "同じ技を全景、手元、影、客席の背後から見せる。どの距離を本編にするかは未定。",
    bookSources: ["photo_story"],
    inspiration: "全景・細部・人物・移行場面を異なる役割で集める方法を、一つの技を複数距離で読む構成へ移した。" },
  { id: "book-seed-006", recipe: "移行だけを残す", dist: "mid",
    text: "決定的瞬間をすべて省き、入場、持ち替え、息継ぎ、退場だけで事件を語る。",
    bookSources: ["photo_story"],
    inspiration: "物語を支える移行場面と編集・選択の論点から、主事件を見せず周辺の連なりだけで伝える場面にした。" },
  { id: "book-seed-007", recipe: "光の時系列", dist: "mid",
    text: "演者は同じ速さで動くが、光だけが朝から夜へ、次に夜から朝へ進む。",
    bookSources: ["photo_story"],
    inspiration: "時間帯と光の質を物語の感情へ結びつける方法を、身体と光が別の時間を進む場面へ変形した。" },
  { id: "book-seed-008", recipe: "最良像の欠落", dist: "alien",
    text: "最も美しく成功した一回だけを捨て、残った失敗の順序で一つの物語を作る。",
    bookSources: ["photo_story"],
    inspiration: "重複を除いて役割の違う写真を残す編集を、美的な最良像を外して失敗から流れを作る判断へ反転した。" },

  { id: "book-seed-009", recipe: "失敗を受け取る", dist: "near",
    text: "一人が落とした場所から、次の演者が新しい技を始める。拾う人はいない。",
    bookSources: ["improv"],
    inspiration: "相手の提案を受け入れて発展させる考え方を、落下位置を次の演技の提案として扱う連鎖へ変形した。" },
  { id: "book-seed-010", recipe: "身体のイエス・アンド", dist: "mid",
    text: "相手の身振りを否定せず一動作だけ足す。二人の身体が何になるかは決めない。",
    bookSources: ["improv"],
    inspiration: "受容と付加で発想を広げる即興の原則を、言葉を使わない身体の継ぎ足しへ移した。" },
  { id: "book-seed-011", recipe: "客席を聴く", dist: "mid",
    text: "咳、椅子の軋み、遅れた拍手を提案として受け取り、次の動きを一つ変える。",
    bookSources: ["improv"],
    inspiration: "聴く・集中する・相手へ焦点を合わせる訓練を、客席の偶発音を舞台の提案として扱う仕組みにした。" },
  { id: "book-seed-012", recipe: "筋書きの委譲", dist: "alien",
    text: "演者は次を決められない。倒れた物の向きだけが、次の人物と場所を指定する。",
    bookSources: ["improv"],
    inspiration: "筋書きのない状況で柔軟に応答する力を、物の偶然へ場面決定権を渡す制約として変形した。" },

  { id: "book-seed-013", recipe: "音色のすり替え", dist: "near",
    text: "同じ高さの音を木、金属、声、糸で鳴らし、音の持ち主だけが交代していく。",
    bookSources: ["neiro"],
    inspiration: "高さや大きさだけでは捉えられない音色と、発音構造の比較を、同音が素材を渡り歩く場面へ移した。" },
  { id: "book-seed-014", recipe: "声の年齢差", dist: "mid",
    text: "一つの身体から子ども、老年、機械の声が順に出る。身体の年齢は変えない。",
    bookSources: ["neiro"],
    inspiration: "発声法・声質・年齢による声の個性を、身体の見た目と声の時間が一致しない場面へ変形した。" },
  { id: "book-seed-015", recipe: "圧縮で失う", dist: "mid",
    text: "同じ演奏を録音し直すたび細部が消え、最後はリズムの輪郭だけが残る。",
    bookSources: ["neiro"],
    inspiration: "録音・圧縮・再生機器が聴こえへ与える影響を、複製のたび音が骨格化する進行へ移した。" },
  { id: "book-seed-016", recipe: "聞こえない指揮", dist: "alien",
    text: "客には聞こえない高い音だけで演者を動かす。反応から音の形を想像させる。",
    bookSources: ["neiro"],
    inspiration: "周波数や倍音を通じて音色を捉える論点を、不可聴の合図を身体反応から逆算する場面へ変形した。" },

  { id: "book-seed-017", recipe: "開演前を本編にする", dist: "near",
    text: "楽器の調律、床の軋み、装束を整える音だけで、すでに物語が始まっている。",
    bookSources: ["noh_kyogen"],
    inspiration: "能楽堂では調律や空間の静けさから舞台が始まるという鑑賞の入口を、準備音だけの開幕へ変形した。" },
  { id: "book-seed-018", recipe: "省略で風景を呼ぶ", dist: "mid",
    text: "一本の柱を舟、森、牢へ変える。演者は名前を言わず、歩幅だけを変える。",
    bookSources: ["noh_kyogen"],
    inspiration: "簡素な舞台ほど想像の範囲が広がるという論点を、柱と歩幅だけで複数の場所を立ち上げる場面にした。" },
  { id: "book-seed-019", recipe: "緊張と緩和", dist: "mid",
    text: "落下寸前の静止が長いほど、成功後の一言は日常的になる。何を言うかは未定。",
    bookSources: ["noh_kyogen"],
    inspiration: "狂言の笑いを支える緊張と緩和の構造を、高い身体緊張と平凡な発話の落差へ移した。" },
  { id: "book-seed-020", recipe: "橋の時間", dist: "alien",
    text: "舞台へ着くまでの細い通路で一生が進み、本舞台では一秒しか経たない。",
    bookSources: ["noh_kyogen"],
    inspiration: "能楽堂の固有空間と、登場人物を想像しながら見る鑑賞法を、通路と本舞台で異なる時間が流れる構造へ変形した。" },

  { id: "book-seed-021", recipe: "0.2秒のずれ", dist: "near",
    text: "二人のキャッチの間だけを少しずつ延ばす。会話が決裂する瞬間は何秒か。",
    bookSources: ["conversation"],
    inspiration: "話者交替がごく短い間で調整される仕組みを、物の受け渡しにある間が関係を変える場面へ移した。" },
  { id: "book-seed-022", recipe: "聞きながら準備する", dist: "mid",
    text: "相手の動きを見ながら返答の技を準備するが、最後の一拍で意味だけが変わる。",
    bookSources: ["conversation"],
    inspiration: "相手の発話を処理しつつ自分の返答を計画する並行処理を、身体技の準備と意味の更新へ変形した。" },
  { id: "book-seed-023", recipe: "修復の可視化", dist: "mid",
    text: "失敗するたび最初へ戻らず、その場で言い直すように技の形だけを修復する。",
    bookSources: ["conversation"],
    inspiration: "相づち・修復・言い直しで共同理解を維持する会話の仕組みを、技の途中から形を直す運動へ移した。" },
  { id: "book-seed-024", recipe: "曖昧な命令", dist: "alien",
    text: "「そこへ置いて」を二人が別の意味で実行する。二つの正解を同時に残せるか。",
    bookSources: ["conversation"],
    inspiration: "同じ文に複数解釈が生まれ文脈で選ばれる過程を、解釈違いを解消せず並存させる場面へ変形した。" },

  { id: "book-seed-025", recipe: "母音で大きさを変える", dist: "near",
    text: "演者が発する母音に合わせ、同じ道具が大きくも小さくも扱われる。",
    bookSources: ["speech_sound"],
    inspiration: "音の響き自体が大きさなどの印象を持つ音象徴を、声によって物の知覚寸法が変わる場面へ移した。" },
  { id: "book-seed-026", recipe: "舌を投影する", dist: "mid",
    text: "発音中の舌の動きが巨大な影になり、その形を別の演者が全身でなぞる。",
    bookSources: ["speech_sound"],
    inspiration: "MRIやエコーで発音器官の動きを可視化する調音音声学を、口内運動と全身運動の対応へ変形した。" },
  { id: "book-seed-027", recipe: "声の保存", dist: "mid",
    text: "失われる声を一つの器へ保存する。蓋を開けるたび別の身体から聞こえる。",
    bookSources: ["speech_sound"],
    inspiration: "失われる声を残す福祉音声学の論点を、声の記憶が身体を移動する架空の保存装置へ変形した。" },
  { id: "book-seed-028", recipe: "存在しない音", dist: "alien",
    text: "誰も鳴らしていない音を一人だけが聞き、その反応を見て全員が同じ音を演じ始める。",
    bookSources: ["speech_sound"],
    inspiration: "母語の知覚が存在しない音まで聞かせる現象を、個人の聞き違いが集団の現実になる場面へ変形した。" },

  { id: "book-seed-029", recipe: "図だけの稽古", dist: "near",
    text: "言葉を使わず、床に描いた線と物の配置だけで七人が同じ場面を覚える。",
    bookSources: ["visual_thinker"],
    inspiration: "像や空間関係を使う問題解決と手を動かす学習を、図と配置だけで共有する稽古へ移した。" },
  { id: "book-seed-030", recipe: "二つの視覚思考", dist: "mid",
    text: "一人は物の細部を記憶し、一人は空間の構造を変える。交換できない役割は何か。",
    bookSources: ["visual_thinker"],
    inspiration: "具体像を精密に捉える型と形・構造を操作する型の区別を、二人の異なる舞台能力へ変形した。" },
  { id: "book-seed-031", recipe: "手が説明を追い越す", dist: "mid",
    text: "口ではまだ説明できない装置を、手だけが先に組み上げる。名前は完成後につける。",
    bookSources: ["visual_thinker"],
    inspiration: "言語中心の評価では見落とされる制作・技術の能力を、説明より先に手が答えを作る場面へ移した。" },
  { id: "book-seed-032", recipe: "形で選ぶ分岐", dist: "alien",
    text: "観客は言葉でなく三つの形を選び、その輪郭が次の場面の通路になる。",
    bookSources: ["visual_thinker"],
    inspiration: "像や形を使った思考を、観客が形で判断し空間そのものを分岐させる参加構造へ変形した。" },

  { id: "book-seed-033", recipe: "問いを一つにする", dist: "near",
    text: "舞台上の問いは「落ちるか」だけ。物、身体、光が別々の答えを試す。",
    bookSources: ["beautiful_experiments"],
    inspiration: "複雑な自然現象から検証できる一問を切り出す実験設計を、落下という単純な問いを三要素で検証する場面へ移した。" },
  { id: "book-seed-034", recipe: "外れた予想を残す", dist: "mid",
    text: "成功した装置は片づけ、予想外に動いた装置だけを舞台中央へ残して次を始める。",
    bookSources: ["beautiful_experiments"],
    inspiration: "予想が外れた場合にも意味を持つ反証可能な実験を、失敗した装置が次の中心になる構成へ変形した。" },
  { id: "book-seed-035", recipe: "観客が追試する", dist: "mid",
    text: "演者の奇跡を、休憩中に観客が同じ三つの道具で再現できるか試す。",
    bookSources: ["beautiful_experiments"],
    inspiration: "他者が追試できる簡潔さが説得力になるという論点を、舞台の出来事を客席が検証する仕組みへ移した。" },
  { id: "book-seed-036", recipe: "最小装置・最大法則", dist: "alien",
    text: "糸一本と影一つだけで、舞台全体に働く見えない法則を証明する。",
    bookSources: ["beautiful_experiments"],
    inspiration: "限られた技術で測定条件を作り自然原理を明快に示す実験の美しさを、最小の舞台装置へ変形した。" },

  { id: "book-seed-037", recipe: "確率の更新", dist: "near",
    text: "物が落ちるたび、観客が信じる結末を変える。確信が逆転した所で止める。",
    bookSources: ["bayes"],
    inspiration: "新しい証拠によって事前の見込みを更新する考え方を、落下の蓄積で観客の結末予想が変わる場面へ移した。" },
  { id: "book-seed-038", recipe: "誤信を数える", dist: "mid",
    text: "演者の思い込みを床の数字で示す。証拠が増えるほど数字だけが本人から離れる。",
    bookSources: ["bayes"],
    inspiration: "信念の強さを確率として扱い証拠で更新する考え方を、身体と数値が分離していく視覚場面へ変形した。" },
  { id: "book-seed-039", recipe: "客席の事前分布", dist: "mid",
    text: "開演前の投票を光の濃さに変え、舞台上の一事実ごとに照明を塗り替える。",
    bookSources: ["bayes"],
    inspiration: "事前確率と事後確率の関係を、観客の予想を初期照明として証拠ごとに更新する仕組みへ移した。" },
  { id: "book-seed-040", recipe: "同じ証拠・違う確信", dist: "alien",
    text: "同じ足跡を見た二人が正反対の未来を準備する。どちらの過去も明かさない。",
    bookSources: ["bayes"],
    inspiration: "同じ証拠でも事前の見込みが違えば判断が変わる構造を、二人が別の未来へ動く場面へ変形した。" },

  { id: "book-seed-041", recipe: "規格箱の連結", dist: "near",
    text: "同じ大きさの箱が楽屋、舞台、客席を通り、場所ごとに別の役割へ接続する。",
    bookSources: ["container"],
    inspiration: "規格化された箱が船・鉄道・トラックをつなぐ仕組みを、一つの箱が劇場の各領域を接続する場面へ移した。" },
  { id: "book-seed-042", recipe: "裏方の地形変化", dist: "mid",
    text: "運びやすい道具を一つ導入した結果、舞台より先に楽屋の壁と人の動線が変わる。",
    bookSources: ["container"],
    inspiration: "コンテナが港の土地・設備・労働を再編した歴史を、小さな道具が舞台裏の空間を変える因果へ変形した。" },
  { id: "book-seed-043", recipe: "通過する主役", dist: "mid",
    text: "主役は箱の中身ではなく箱そのもの。誰にも開けられず、引き渡しだけが続く。",
    bookSources: ["container"],
    inspiration: "内容物を積み替えず運ぶ規格箱の機能を、開封されない物と受け渡す人々の関係へ変形した。" },
  { id: "book-seed-044", recipe: "効率への抵抗", dist: "alien",
    text: "完璧に速い搬入へ、一人だけが古い結び方で抵抗する。その遅さを残す理由は未定。",
    bookSources: ["container"],
    inspiration: "技術導入が労働の縮小・再編と抵抗を生んだ論点を、効率化された現場に残る手仕事の遅さへ移した。" },

  { id: "book-seed-045", recipe: "七つの視点", dist: "near",
    text: "同じ落下を、演者、物、床、音、照明、客席、翌日の視点から七回見る。",
    bookSources: ["viewpoints"],
    inspiration: "異分野の専門家との対話から視点を増やす構成を、一つの出来事を七つの立場と時間から読む場面へ変形した。" },
  { id: "book-seed-046", recipe: "視点の椅子", dist: "mid",
    text: "座る椅子を替えるたび、同じ人物が加害者、救助者、目撃者に見え直す。",
    bookSources: ["viewpoints"],
    inspiration: "立場や学問が前提を変え、同じ対象の見え方を更新する論点を、座る位置で人物の役割が変わる場面へ移した。" },
  { id: "book-seed-047", recipe: "答えよりレンズ", dist: "mid",
    text: "七人は結論を言わず、自分が何を見落とす視点なのかだけを告白する。",
    bookSources: ["viewpoints"],
    inspiration: "正解を一つ得るより複数の見方を持つ教養の意義を、各視点の死角を提示する場面へ変形した。" },
  { id: "book-seed-048", recipe: "物からの視線", dist: "alien",
    text: "観客席を舞台上の道具から見返す。人間側の正面は最後まで一度も見せない。",
    bookSources: ["viewpoints"],
    inspiration: "自明な人間中心の立場をずらす視点の訓練を、物を観察主体にした一方向の構図へ移した。" },

  { id: "book-seed-049", recipe: "事実・解釈・仮説", dist: "near",
    text: "見えた動き、意味づけ、次の予想を三色の床へ置き分ける。混ざった所だけ踊る。",
    bookSources: ["observation"],
    inspiration: "事実・解釈・仮説を区別する観察法を、三色の場所と身体の移動で見えるように変形した。" },
  { id: "book-seed-050", recipe: "観察者を動かす", dist: "mid",
    text: "対象は動かない。観察者だけが近づき、伏せ、背を向け、見えた事実を変える。",
    bookSources: ["observation"],
    inspiration: "観察は対象だけでなく観察者との関係で変わるという論点を、見る身体だけが変化する場面へ移した。" },
  { id: "book-seed-051", recipe: "死角を主役にする", dist: "mid",
    text: "全員が見た場面では何も起きず、誰も見ていない隅だけが少しずつ変わる。",
    bookSources: ["observation"],
    inspiration: "認知バイアスや見落としを点検する観察の循環を、注意の外側だけに変化が蓄積する場面へ変形した。" },
  { id: "book-seed-052", recipe: "曖昧さを保留する", dist: "alien",
    text: "正体を決める名前を禁じ、同じ物を七通りに扱う。最後も答えを出さない。",
    bookSources: ["observation"],
    inspiration: "曖昧さを急いで解消せず見方を更新する態度を、命名せず複数の扱いを残す場面へ移した。" },

  { id: "book-seed-053", recipe: "発想を寝かせる", dist: "near",
    text: "未完成の技を箱へしまい、三場面後に別の演者が続きを始める。",
    bookSources: ["thinking"],
    inspiration: "発想を急いで完成させず時間と距離を置いて育てる思考法を、未完成の動作を後で他者が継ぐ構成へ変形した。" },
  { id: "book-seed-054", recipe: "忘却で削る", dist: "mid",
    text: "覚えている部分だけで同じ場面を翌日作り直す。消えた細部は復元しない。",
    bookSources: ["thinking"],
    inspiration: "忘れることが情報を整理し重要なものを残す働きになる論点を、記憶だけで再制作するルールへ移した。" },
  { id: "book-seed-055", recipe: "問いの交差", dist: "mid",
    text: "答えのない問いを二枚引き、両方に答える一つの身体動作だけを探す。",
    bookSources: ["thinking"],
    inspiration: "短い問いや断片を組み替えて考えを進める発想法を、二問を一動作で接続する稽古へ変形した。" },
  { id: "book-seed-056", recipe: "題名を遅らせる", dist: "alien",
    text: "題名なしで最後まで演じ、観客が帰った後に床の痕跡から一語だけ選ぶ。",
    bookSources: ["thinking"],
    inspiration: "先に名前で思考を固定せず、素材を動かしながら整理する態度を、終演後に題名を決める手順へ移した。" },

  { id: "book-seed-057", recipe: "欲求と障害", dist: "near",
    text: "一人はただ物を拾いたい。床だけが毎回違う理由でそれを拒む。",
    bookSources: ["story_notebook"],
    inspiration: "人物の欲求と葛藤から行動を生む創作単位を、単純な欲求と変化する床の抵抗へ変形した。" },
  { id: "book-seed-058", recipe: "制度を身体化する", dist: "mid",
    text: "舞台の法律は「左手で渡した物は返せない」。関係が壊れるまで説明しない。",
    bookSources: ["story_notebook"],
    inspiration: "世界の制度やルールを出来事へ結びつける方法を、一つの受け渡し規則が人間関係を変える場面へ移した。" },
  { id: "book-seed-059", recipe: "因果の骨組み", dist: "mid",
    text: "床の傷から始め、その原因を三つの行動だけで逆向きに組み立てる。",
    bookSources: ["story_notebook"],
    inspiration: "出来事の因果・転換・結末を設計するプロットの論点を、結果の痕跡から原因へ戻る短い構成にした。" },
  { id: "book-seed-060", recipe: "説明を動作へ移す", dist: "alien",
    text: "世界の秘密を語る台詞を全部消し、靴を脱ぐ順番だけで観客に推測させる。",
    bookSources: ["story_notebook"],
    inspiration: "情報説明ではなく行動・会話・感覚で場面を立ち上げる方法を、説明台詞を一つの所作へ圧縮した。" },

  { id: "book-seed-061", recipe: "気候から道具を作る", dist: "near",
    text: "風が止まらない土地の道具は、置くためでなく飛ばされ続けるために作られている。",
    bookSources: ["fantasy_world"],
    inspiration: "環境・気候・生活・技術を因果で接続して世界を作る論点を、風を前提にした道具の機能へ変形した。" },
  { id: "book-seed-062", recipe: "魔法のインフラ", dist: "mid",
    text: "奇跡は一人の才能でなく、床下の配管から毎朝配られる。止まった日の場面を作る。",
    bookSources: ["fantasy_world"],
    inspiration: "魔法を社会制度・技術・生活へ接続する世界構築を、供給網を持つ日常インフラとして扱う場面へ変形した。" },
  { id: "book-seed-063", recipe: "階級を高さで示す", dist: "mid",
    text: "身分が高いほど低い場所へ立つ国。最下段の人物へ全員が見上げる。",
    bookSources: ["fantasy_world"],
    inspiration: "社会階層や制度を空間・衣服・生活へ反映する方法を、上下の意味を反転した舞台配置へ変形した。" },
  { id: "book-seed-064", recipe: "地図の外側", dist: "alien",
    text: "地図にない一歩を踏むと、衣装の素材と話す言葉が同時に変わる。",
    bookSources: ["fantasy_world"],
    inspiration: "地理・文化・言語・物質を一貫した世界として結ぶ方法を、境界越えで複数の規則が変わる場面へ移した。" },

  { id: "book-seed-065", recipe: "欠落を手がかりにする", dist: "near",
    text: "七個あるはずの道具が六個しかない。技より先に、空いた場所を見せ続ける。",
    bookSources: ["mystery"],
    inspiration: "違和感を中心の問いへ変え、追える情報を渡すミステリの約束を、欠けた配置が主導する場面へ変形した。" },
  { id: "book-seed-066", recipe: "光の誤誘導", dist: "mid",
    text: "照明は毎回、重要でない手だけを追う。本当の手がかりは暗闇で音を立てる。",
    bookSources: ["mystery"],
    inspiration: "伏線・誤誘導・視点制限で情報の読み方を設計する方法を、光と音が別の重要度を示す場面へ移した。" },
  { id: "book-seed-067", recipe: "観客と同条件", dist: "mid",
    text: "演者も観客も同じ三つの手がかりしか持たない。先に気づいた側が場面を止める。",
    bookSources: ["mystery"],
    inspiration: "読者が追える情報を公平に渡して解決へ導く契約を、舞台と客席が同条件で推理する構造へ変形した。" },
  { id: "book-seed-068", recipe: "解決で過去を変える", dist: "alien",
    text: "最後の一音で、前の六場面がすべて別の意味に聞こえ直す。",
    bookSources: ["mystery"],
    inspiration: "結末で問いを回収し、既出情報が検証可能な別の意味を持つ解決を、一音による全場面の再解釈へ移した。" },

  { id: "book-seed-069", recipe: "遠い棚を衝突させる", dist: "near",
    text: "技の本と料理の本を一冊ずつ開き、同じ動詞が出た所だけを一場面にする。",
    bookSources: ["random_reading"],
    inspiration: "目的を決めず異分野を読むことで思いがけない接続を得る乱読を、二冊の共通動詞から作る場面へ変形した。" },
  { id: "book-seed-070", recipe: "忘れた断片の帰還", dist: "mid",
    text: "忘れていた三枚のメモを順不同で置き、最も関係の薄い二枚だけを採用する。",
    bookSources: ["random_reading"],
    inspiration: "忘却や時間が知識を淘汰し偶然の発見を生むという論点を、古い断片の弱い関係を選ぶ操作へ変形した。" },
  { id: "book-seed-071", recipe: "間違った棚", dist: "mid",
    text: "すべての道具を一度だけ別の演目の棚へ戻す。翌日、誤配置を直さず稽古する。",
    bookSources: ["random_reading"],
    inspiration: "ジャンルを限らず手当たり次第に読む価値を、誤分類された道具から別の用法を発見する稽古へ移した。" },
  { id: "book-seed-072", recipe: "読み手が完成させる", dist: "alien",
    text: "演者は場面の半分で去り、残り半分は観客が見た順番によってだけ存在する。",
    bookSources: ["random_reading"],
    inspiration: "読み手の存在が本の意味を完成させるという論点を、観客の記憶順が後半を作る未完の舞台へ変形した。" },

  { id: "book-seed-073", recipe: "四要素の演技", dist: "near",
    text: "火、水、空気、油を四人の動きに置き換え、一つの物へ別々の変化を与える。",
    bookSources: ["cooking_tetrahedron"],
    inspiration: "料理を火・水・空気・油が素材へ与える作用として捉えるモデルを、四人の身体作用へ変形した。" },
  { id: "book-seed-074", recipe: "遠い技の同型", dist: "mid",
    text: "投げる技と乾かす料理を、待つ時間と水分の減少だけで同じ構造にする。",
    bookSources: ["cooking_tetrahedron"],
    inspiration: "一見遠い料理を素材へ働く原理から比較する方法を、身体技と調理を作用の同型としてつなげた。" },
  { id: "book-seed-075", recipe: "名前より作用", dist: "mid",
    text: "技名をすべて隠し、回す、湿らす、浮かす、焦がすの四作用だけで順番を組む。",
    bookSources: ["cooking_tetrahedron"],
    inspiration: "料理名や地域より先に素材へ何が作用したかを見る分類法を、演技を作用動詞だけで再編集する方法へ移した。" },
  { id: "book-seed-076", recipe: "生と加工の境界", dist: "alien",
    text: "同じ物を触れない、温める、濡らす、油を塗るの順で別の存在として紹介する。",
    bookSources: ["cooking_tetrahedron"],
    inspiration: "少数要素の組み合わせで料理の分類を捉え直す論点を、同一物の状態ごとに役名が変わる場面へ変形した。" },

  { id: "book-seed-077", recipe: "緊張と弛緩の身体化", dist: "near",
    text: "音が緊張するほど身体はほどけ、音が落ち着くほど糸だけが強く張る。",
    bookSources: ["brain_music"],
    inspiration: "和音や調性が緊張と弛緩を作る仕組みを、音と身体・糸が逆向きに緊張する場面へ変形した。" },
  { id: "book-seed-078", recipe: "周波数を場所にする", dist: "mid",
    text: "低い音は床、高い音は天井から来る。演者は聞こえた高さへ身体を移す。",
    bookSources: ["brain_music"],
    inspiration: "空気振動の周波数を耳と脳が高さとして処理する道筋を、音高と舞台上の高さを直結させる場面へ移した。" },
  { id: "book-seed-079", recipe: "不協和の距離", dist: "mid",
    text: "二人が近づくほど音は濁り、離れるほど一つの和音になる。接触する理由は未定。",
    bookSources: ["brain_music"],
    inspiration: "音程と和声が協和・不協和を生む関係を、二人の物理距離が響きを変える場面へ変形した。" },
  { id: "book-seed-080", recipe: "予測を外す終止", dist: "alien",
    text: "終わるはずの響きで毎回別の動作が始まる。七回目だけ本当に終える。",
    bookSources: ["brain_music"],
    inspiration: "カデンツが聴き手に終止を予測させる仕組みを、予測を反復して裏切る動作構成へ変形した。" },

  { id: "book-seed-081", recipe: "楽しい命令", dist: "near",
    text: "明るい合唱の振付を真似するうち、観客が舞台上の物を同じ方向へ運んでいる。",
    bookSources: ["propaganda"],
    inspiration: "娯楽の形を取るメッセージが自発的な参加を促す危うさを、楽しい模倣が労働へ変わる場面にした。" },
  { id: "book-seed-082", recipe: "意図の後出し", dist: "mid",
    text: "最初は遊びとして同じ印を集める。意味を明かすのは全員が身につけた後。",
    bookSources: ["propaganda"],
    inspiration: "魅力的な表現を楽しむうちに思想や帰属を受け取る構造を、記号の意味を後から明かす参加へ変形した。" },
  { id: "book-seed-083", recipe: "反復する標語", dist: "mid",
    text: "意味のない短文を七回唱える。回数ごとに照明が正しさだけを強めていく。",
    bookSources: ["propaganda"],
    inspiration: "標語・音楽・映像の反復がメッセージを自然化する仕組みを、照明が確信を補強する場面へ移した。" },
  { id: "book-seed-084", recipe: "魅力と警戒の同居", dist: "alien",
    text: "最も美しい場面の端に、誰が得をする演出かを示す小さな数字が残り続ける。",
    bookSources: ["propaganda"],
    inspiration: "表現の魅力を否定せず、その背後の主体と目的を検証する視点を、画面内の消えない注記へ変形した。" },

  { id: "book-seed-085", recipe: "モーラで運ぶ", dist: "near",
    text: "四拍に収まる言葉だけで道具を渡す。音が余ったら身体を一度止める。",
    bookSources: ["linguistic_rap"],
    inspiration: "モーラや音節をラップのリズムへ配置する考え方を、発話の長さが受け渡しと静止を決める場面へ移した。" },
  { id: "book-seed-086", recipe: "韻が物を引く", dist: "mid",
    text: "似た母音の言葉を言うたび、離れた二つの道具が一歩ずつ近づく。",
    bookSources: ["linguistic_rap"],
    inspiration: "音の対応が韻として感じられる仕組みを、似た響きが物理的な引力になる場面へ変形した。" },
  { id: "book-seed-087", recipe: "声質の役割交換", dist: "mid",
    text: "台詞は同じまま、声質だけを交換すると、主役と脇役の位置が入れ替わる。",
    bookSources: ["linguistic_rap"],
    inspiration: "声質・発声・明瞭度が話者の表現とアイデンティティを作る論点を、声だけで配役が変わる場面へ移した。" },
  { id: "book-seed-088", recipe: "二重の意味", dist: "alien",
    text: "一つの言葉を二つの意味で聞き、左右の演者が正反対の動作を同時に始める。",
    bookSources: ["linguistic_rap"],
    inspiration: "多義性・比喩・文脈で意味を重ねる言葉遊びを、一語から二方向の身体反応が生まれる場面へ変形した。" },

  { id: "book-seed-089", recipe: "配置だけ変える", dist: "near",
    text: "同じ三つの動作を高さだけ変えて重ねる。組み合わせは同じでも関係が変わる。",
    bookSources: ["chord_theory"],
    inspiration: "同じコードでも構成音の配置や省略で響きが変わるボイシングを、動作の高さだけを変える構成へ移した。" },
  { id: "book-seed-090", recipe: "帰る場所を作る", dist: "mid",
    text: "どれだけ遠い動きをしても、同じ床板へ戻る。その板を最後に外す。",
    bookSources: ["chord_theory"],
    inspiration: "進行の安定点となるトニックの機能を、身体が帰還する一枚の床として扱い、最後に消す場面へ変形した。" },
  { id: "book-seed-091", recipe: "一音ぶんの異物", dist: "mid",
    text: "整った六人の動きへ一人だけ余分な角度を足し、緊張を消さず次へ渡す。",
    bookSources: ["chord_theory"],
    inspiration: "基本和音へ音を加えて色彩と緊張を作るテンションを、集団運動に残る一つの異角度へ変形した。" },
  { id: "book-seed-092", recipe: "終止を延期する", dist: "alien",
    text: "終わりへ向かう三動作の最後だけを毎回別の人物へ渡し、誰も完結できない。",
    bookSources: ["chord_theory"],
    inspiration: "和声進行の方向感と終止機能を、結末動作が演者間を移動して解決を延期する構成へ変形した。" },

  { id: "book-seed-093", recipe: "音で性格をつける", dist: "near",
    text: "丸い響きの名を呼ぶと身体が曲がり、硬い響きの名では関節が直線になる。",
    bookSources: ["naming"],
    inspiration: "名前の音・文字・リズムが人物の印象を作る設計を、呼び名が身体の形を変える場面へ移した。" },
  { id: "book-seed-094", recipe: "地名の共通規則", dist: "mid",
    text: "舞台の四隅に同じ語尾の地名をつける。中央だけは呼ぶたび違う音になる。",
    bookSources: ["naming"],
    inspiration: "同じ地域の地名に共通する言語感を持たせる方法を、四隅の規則と中央の例外へ変形した。" },
  { id: "book-seed-095", recipe: "名前を失う道具", dist: "mid",
    text: "道具の名前を消すと、演者は本来の使い方を忘れ、触感だけで新しい用途を探す。",
    bookSources: ["naming"],
    inspiration: "名前が機能・歴史・役割を伝える設計であるという論点を、命名を外して用途を作り直す場面へ反転した。" },
  { id: "book-seed-096", recipe: "似すぎた名前", dist: "alien",
    text: "一音だけ違う二人の名を呼ぶたび、別の人物が返事をする。訂正しないまま進める。",
    bookSources: ["naming"],
    inspiration: "似すぎる名前や発音しにくい名前を点検する原則を、混同を欠陥でなく関係を揺らす仕掛けへ変形した。" },

  { id: "book-seed-097", recipe: "履歴が宿る物", dist: "near",
    text: "古い道具を持つと、前の持ち主が最後にした動作を一度だけ繰り返してしまう。",
    bookSources: ["mysteries"],
    inspiration: "使われた履歴や持ち主の感情を物に宿る異変として扱う発想を、一回だけ再生される身体記憶へ変形した。" },
  { id: "book-seed-098", recipe: "植物の時間", dist: "mid",
    text: "演者の一分が植物の百年。芽、森、枯死を同じ身体の速度差だけで見せる。",
    bookSources: ["mysteries"],
    inspiration: "植物や自然が持つ人間とは異なる時間と生態を怪異へ生かす論点を、時間尺度の違う身体表現へ移した。" },
  { id: "book-seed-099", recipe: "出現条件を作る", dist: "mid",
    text: "客席の半分が目を閉じた時だけ現れる人物。見た者と見ない者の説明が食い違う。",
    bookSources: ["mysteries"],
    inspiration: "怪異の目的・弱点・出現条件を設計する方法を、観客の視認状態で存在が変わる場面へ移した。" },
  { id: "book-seed-100", recipe: "弱点から輪郭を出す", dist: "alien",
    text: "光では見えない存在が、床の塩を避ける動きだけで輪郭を現す。",
    bookSources: ["mysteries"],
    inspiration: "姿や能力を直接描かず、禁忌や弱点から怪異を設計する方法を、避ける動線で存在を示す場面へ変形した。" },
];
