from pathlib import Path
from playwright.sync_api import sync_playwright
import json
D=Path(__file__).resolve().parent
checks=[]
def check(label,condition):
 assert condition,label
 checks.append({'check':label,'passed':True})
with sync_playwright() as p:
 b=p.chromium.launch();page=b.new_page(viewport={'width':1280,'height':1000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:8936/handoff-2026-09-09.html',wait_until='networkidle')
 click=lambda id:page.locator('#'+id).click()
 txt=lambda id:page.locator('#'+id).inner_text()
 val=lambda id:page.locator('#'+id).input_value()
 person=lambda id:page.locator(f'[data-person="{id}"]').inner_text()
 def preset(value):page.locator('#preset').select_option(value)
 def step(count=1):
  for _ in range(count):click('next-boundary')
 check('版を照合して操作を有効化',not page.locator('#start-handoff').is_disabled() and not page.locator('#load-error').is_visible())
 check('未割当の人を作業終了と表示しない','登録作業なし' in person('D'))
 click('start-handoff');step();click('try-cue')
 check('3秒では担当を外さず机を置いている',txt('handoff-time')=='3秒' and '机を置く' in person('A') and '机を置く' in person('B'))
 check('準備前の合図は進めなかった履歴を残す','進めず' in txt('cue-log') and '準備を終えていません' in txt('cue-reason'))
 step()
 check('5秒でAは残りBだけ別作業へ',txt('handoff-time')=='5秒' and '机を置いて待つ' in person('A') and '別作業へ移動' in person('B'))
 page.screenshot(path=str(D/'handoff-trial-desktop-2026-09-09.png'),full_page=True)
 page.locator('#crew-section').screenshot(path=str(D/'handoff-trial-people-2026-09-09.png'))
 step(3)
 check('10秒で準備完了しても早い合図では再開しない',txt('handoff-time')=='10秒' and '明示的な再開待ち' in txt('handoff-status') and page.locator('#moving-table').get_attribute('transform')=='translate(250 125)' and '条件が揃ったとして' in txt('try-cue'))
 click('pause-handoff');page.locator('#try-cue').dispatch_event('click');page.locator('#plus-one').dispatch_event('click')
 check('全体停止は時計と合図と人別表示を止める',txt('handoff-time')=='10秒' and '全体一時停止' in person('A') and '進めず' in txt('cue-log'))
 click('pause-handoff');click('try-cue')
 check('再開時に終点へ飛ばない',page.locator('#moving-table').get_attribute('transform')=='translate(250 125)' and '机を下手袖へ運ぶ' in person('C'))
 step()
 check('通常例は15秒で全作業が終了',txt('handoff-time')=='15秒' and '全作業が終了' in txt('handoff-status'))
 click('reset-handoff')
 check('リセットで通過履歴を消す',txt('handoff-time')=='0秒' and 'まだ合図を' in txt('cue-log'))
 preset('slow');click('start-handoff');step(4)
 check('Cが遅れてもBは別作業を終える',txt('handoff-time')=='10秒' and '登録作業は終了' in person('B') and '机を置いて待つ' in person('A'))
 preset('conflict');click('start-handoff');step(3)
 check('二重割当は両対象を表示し自動で順序付けしない','担当が重なる：C' in txt('trial-issues') and 'Cの別の作業' in txt('trial-issues') and 'Cが平台から机へ移動' in txt('trial-issues'))
 preset('cycle');click('start-handoff');step(2)
 check('循環を示しつつ机を置くところまでは進める','互いに待っている' in txt('trial-issues') and txt('handoff-time')=='5秒')
 preset('missing');click('start-handoff');step(3)
 check('未定担当を消さず不成立として表示','未定' in txt('trial-issues') and '全作業が終了' not in txt('handoff-status'))
 preset('candidate');page.locator('#sequence').evaluate('(el)=>el.open=true')
 check('候補は自動配員せず区間表にも未確定を残す','候補B/C（未確定）' in txt('segment-rows') and '未確定' in txt('trial-issues'))
 page.locator('#person-view').select_option('A')
 page.locator('#sequence').evaluate('(el)=>el.open=false');page.evaluate("window.dispatchEvent(new Event('beforeprint'))");page.emulate_media(media='print')
 check('印刷に候補と表示範囲と他作業条件を残す',page.locator('#trial-issues').is_visible() and page.locator('#segment-rows').is_visible() and '候補B/C' in txt('segment-rows') and '表示範囲：A' in txt('print-scope') and not page.locator('#start-handoff').is_visible())
 page.screenshot(path=str(D/'handoff-trial-print-2026-09-09.png'),full_page=True)
 page.emulate_media(media='screen');page.evaluate("window.dispatchEvent(new Event('afterprint'))");check('印刷後に区間表の開閉状態を戻す',not page.locator('#sequence').evaluate('(el)=>el.open'));page.locator('#person-view').select_option('all')
 preset('return');click('start-handoff');step(5)
 check('Bが別作業から戻る例が動く',txt('handoff-time')=='12秒' and '持ち直す' in person('B') and '持ち直す' in person('A'))
 preset('full');click('start-handoff');step(2)
 check('全員交代でA/Bがともに離れる','別作業へ移動' in person('A') and '別作業へ移動' in person('B'))
 preset('direct');click('start-handoff');step(3)
 check('手渡し中はA/B/Cが同時に関わる',txt('handoff-time')=='8秒' and all('受け渡す' in person(x) for x in ['A','B','C']))
 step();check('受渡し終了後にBが離れる',txt('handoff-time')=='10秒' and '別作業へ移動' in person('B'))
 preset('normal');page.locator('#settings').evaluate('(el)=>el.open=true');page.locator('#after-right').select_option('D')
 check('区間担当の編集で設定と試しを同期する',val('after-right')=='D' and txt('handoff-time')=='0秒' and 'D' in txt('scenario-description'))
 click('undo-config');check('設定の取消しで前案へ戻せる',val('after-right')=='C' and val('preset')=='normal')
 page.locator('#put-seconds').fill('');page.locator('#put-seconds').dispatch_event('change');click('start-handoff');step()
 check('空欄を0秒とせず工程を止める','所要が未定' in txt('trial-issues') and txt('handoff-time')=='3秒')
 page.locator('#put-seconds').fill('100');page.locator('#put-seconds').dispatch_event('change')
 check('所要範囲外は入力エラーで進行操作を止める',page.locator('#configuration-error').is_visible() and page.locator('#plus-one').is_disabled())
 preset('normal');click('start-handoff');step(2);page.locator('#person-view').select_option('B');page.locator('#sequence').evaluate('(el)=>el.open=true')
 check('担当別で表示を絞り、元の工程条件を残す',not page.locator('[data-person="A"]').is_visible() and '机を置く' in txt('segment-rows'))
 page.locator('#person-view').select_option('all');page.locator('#sequence').evaluate('(el)=>el.open=false');page.locator('#settings').evaluate('(el)=>el.open=false')
 page.set_viewport_size({'width':390,'height':844});page.evaluate('scrollTo(0,0)');page.screenshot(path=str(D/'handoff-trial-mobile-2026-09-09.png'),full_page=True)
 check('携帯幅で本文の横はみ出しなし',page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
 page.locator('#crew-section').scroll_into_view_if_needed();page.screenshot(path=str(D/'handoff-trial-mobile-people-2026-09-09.png'))
 page.reload(wait_until='networkidle');check('再読込みは初期例と0秒に戻す',txt('handoff-time')=='0秒' and val('preset')=='normal')
 check('ブラウザ実行エラーなし',not errors)
 bad=b.new_page(viewport={'width':1280,'height':1000});bad_errors=[];bad.on('pageerror',lambda e:bad_errors.append(str(e)))
 stale=(D/'handoff-core-2026-09-09.mjs').read_text().replace("VERSION='handoff-2026-09-09-r3'","VERSION='stale'")
 bad.route('**/handoff-core-2026-09-09.mjs*',lambda route:route.fulfill(status=200,body=stale,content_type='text/javascript'))
 bad.goto('http://127.0.0.1:8936/handoff-2026-09-09.html',wait_until='networkidle')
 check('古い外部JSが混ざると操作を有効にしない',bad.locator('#start-handoff').is_disabled() and bad.locator('#load-error').is_visible() and any('版が揃っていません' in e for e in bad_errors))
 b.close()
(D/'handoff-browser-checks-2026-09-09.json').write_text(json.dumps({'scope':'Standalone fictional handoff trial only','checks':checks,'page_errors':errors},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'passed':len(checks),'errors':errors},ensure_ascii=False))
